/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courseworkprototype;

/**
 *
 * @author natja
 */
public class OrderRice extends javax.swing.JFrame {

    /**
     * Creates new form OrderRice
     */
    public OrderRice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        KingPrawnFriedRice = new javax.swing.JButton();
        ShrimpFriedRice = new javax.swing.JButton();
        SingaporeFriedRice = new javax.swing.JButton();
        MushroomFriedRice = new javax.swing.JButton();
        SweetCornFriedRice = new javax.swing.JButton();
        EggFriedRice = new javax.swing.JButton();
        YungChowFriedRice = new javax.swing.JButton();
        ShreddedDickFriedRice = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ChickenFriedRice = new javax.swing.JButton();
        BeefFriedRice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        KingPrawnFriedRice.setText("King Prawn Fried Rice");
        KingPrawnFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KingPrawnFriedRiceActionPerformed(evt);
            }
        });

        ShrimpFriedRice.setText("Shrimp Fried Rice");
        ShrimpFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShrimpFriedRiceActionPerformed(evt);
            }
        });

        SingaporeFriedRice.setText("Singapore Fried Rice");
        SingaporeFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingaporeFriedRiceActionPerformed(evt);
            }
        });

        MushroomFriedRice.setText("Mushroom Fried Rice");
        MushroomFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomFriedRiceActionPerformed(evt);
            }
        });

        SweetCornFriedRice.setText("Sweet Corn Fried Rice");
        SweetCornFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SweetCornFriedRiceActionPerformed(evt);
            }
        });

        EggFriedRice.setText("Egg Fried Rice");
        EggFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EggFriedRiceActionPerformed(evt);
            }
        });

        YungChowFriedRice.setText("Yung Chow Fried Rice");
        YungChowFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YungChowFriedRiceActionPerformed(evt);
            }
        });

        ShreddedDickFriedRice.setText("Shredded Duck Fried Rice");
        ShreddedDickFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShreddedDickFriedRiceActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setText("Rice Dishes");

        ChickenFriedRice.setText("Chicken Fried Rice");
        ChickenFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenFriedRiceActionPerformed(evt);
            }
        });

        BeefFriedRice.setText("Beef Fried Rice");
        BeefFriedRice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefFriedRiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ShrimpFriedRice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(KingPrawnFriedRice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(BeefFriedRice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChickenFriedRice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SingaporeFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MushroomFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SweetCornFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EggFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(YungChowFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(ShreddedDickFriedRice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Back)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MushroomFriedRice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ChickenFriedRice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeefFriedRice)
                    .addComponent(SweetCornFriedRice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EggFriedRice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(KingPrawnFriedRice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShrimpFriedRice)
                    .addComponent(YungChowFriedRice))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SingaporeFriedRice)
                    .addComponent(ShreddedDickFriedRice))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        OrderMain f2= new  OrderMain();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void KingPrawnFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KingPrawnFriedRiceActionPerformed
        int menuID = 13;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_KingPrawnFriedRiceActionPerformed

    private void MushroomFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomFriedRiceActionPerformed
        int menuID = 16;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_MushroomFriedRiceActionPerformed

    private void ShreddedDickFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShreddedDickFriedRiceActionPerformed
        int menuID = 20;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_ShreddedDickFriedRiceActionPerformed

    private void ChickenFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenFriedRiceActionPerformed
        int menuID = 11;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_ChickenFriedRiceActionPerformed

    private void BeefFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefFriedRiceActionPerformed
        int menuID = 12;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_BeefFriedRiceActionPerformed

    private void ShrimpFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShrimpFriedRiceActionPerformed
        int menuID = 14;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_ShrimpFriedRiceActionPerformed

    private void SingaporeFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingaporeFriedRiceActionPerformed
        int menuID = 15;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_SingaporeFriedRiceActionPerformed

    private void SweetCornFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SweetCornFriedRiceActionPerformed
        int menuID = 17;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_SweetCornFriedRiceActionPerformed

    private void EggFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EggFriedRiceActionPerformed
        int menuID = 18;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_EggFriedRiceActionPerformed

    private void YungChowFriedRiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YungChowFriedRiceActionPerformed
        int menuID = 19;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_YungChowFriedRiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderRice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderRice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderRice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderRice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderRice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BeefFriedRice;
    private javax.swing.JButton ChickenFriedRice;
    private javax.swing.JButton EggFriedRice;
    private javax.swing.JButton KingPrawnFriedRice;
    private javax.swing.JButton MushroomFriedRice;
    private javax.swing.JButton ShreddedDickFriedRice;
    private javax.swing.JButton ShrimpFriedRice;
    private javax.swing.JButton SingaporeFriedRice;
    private javax.swing.JButton SweetCornFriedRice;
    private javax.swing.JButton YungChowFriedRice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
