/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courseworkprototype;

/**
 *
 * @author natja
 */
public class OrderVegetarian extends javax.swing.JFrame {

    /**
     * Creates new form OrderVegetarian
     */
    public OrderVegetarian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TofuCurry = new javax.swing.JButton();
        TofuChowMein = new javax.swing.JButton();
        SpicyVegetableCurry = new javax.swing.JButton();
        SpicyVegetableChowMein = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VegetableChowMein = new javax.swing.JButton();
        VegetableCurry = new javax.swing.JButton();
        FakeChickenCurry = new javax.swing.JButton();
        FakeChickenChowMein = new javax.swing.JButton();
        MushroomChowMein = new javax.swing.JButton();
        MushroomCurry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        TofuCurry.setText("Tofu Curry");
        TofuCurry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TofuCurryActionPerformed(evt);
            }
        });

        TofuChowMein.setText("Tofu Chow Mein ");
        TofuChowMein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TofuChowMeinActionPerformed(evt);
            }
        });

        SpicyVegetableCurry.setText("Spicy Vegetable Curry");
        SpicyVegetableCurry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpicyVegetableCurryActionPerformed(evt);
            }
        });

        SpicyVegetableChowMein.setText("Spicy Vegetable Chow Mein");
        SpicyVegetableChowMein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpicyVegetableChowMeinActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setText("Vegetarian Dishes");

        VegetableChowMein.setText("Vegetable Chow Mein");
        VegetableChowMein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetableChowMeinActionPerformed(evt);
            }
        });

        VegetableCurry.setText("Vegetable Curry");
        VegetableCurry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VegetableCurryActionPerformed(evt);
            }
        });

        FakeChickenCurry.setText("Fake Chicken Curry");
        FakeChickenCurry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakeChickenCurryActionPerformed(evt);
            }
        });

        FakeChickenChowMein.setText("Fake Chicken Chow Mein");
        FakeChickenChowMein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FakeChickenChowMeinActionPerformed(evt);
            }
        });

        MushroomChowMein.setText("Mushroom Chow Mein");
        MushroomChowMein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomChowMeinActionPerformed(evt);
            }
        });

        MushroomCurry.setText("Mushroom Curry");
        MushroomCurry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MushroomCurryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back)
                .addGap(116, 116, 116)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FakeChickenChowMein, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(MushroomChowMein, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FakeChickenCurry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpicyVegetableCurry, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SpicyVegetableChowMein, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TofuChowMein, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VegetableChowMein, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VegetableCurry, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MushroomCurry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TofuCurry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VegetableChowMein)
                    .addComponent(MushroomCurry))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TofuCurry)
                    .addComponent(VegetableCurry))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TofuChowMein)
                    .addComponent(FakeChickenCurry))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FakeChickenChowMein)
                    .addComponent(SpicyVegetableCurry))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MushroomChowMein)
                    .addComponent(SpicyVegetableChowMein))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        OrderMain f2= new  OrderMain();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void FakeChickenCurryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakeChickenCurryActionPerformed
        int menuID = 33;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_FakeChickenCurryActionPerformed

    private void SpicyVegetableCurryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpicyVegetableCurryActionPerformed
        int menuID = 39;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_SpicyVegetableCurryActionPerformed

    private void VegetableChowMeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegetableChowMeinActionPerformed
        int menuID = 31;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_VegetableChowMeinActionPerformed

    private void VegetableCurryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VegetableCurryActionPerformed
        int menuID = 28;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_VegetableCurryActionPerformed

    private void FakeChickenChowMeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FakeChickenChowMeinActionPerformed
        int menuID = 34;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_FakeChickenChowMeinActionPerformed

    private void MushroomChowMeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomChowMeinActionPerformed
        int menuID = 35;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_MushroomChowMeinActionPerformed

    private void MushroomCurryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MushroomCurryActionPerformed
        int menuID = 24;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_MushroomCurryActionPerformed

    private void TofuCurryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TofuCurryActionPerformed
        int menuID = 37;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_TofuCurryActionPerformed

    private void TofuChowMeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TofuChowMeinActionPerformed
        int menuID = 38;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_TofuChowMeinActionPerformed

    private void SpicyVegetableChowMeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpicyVegetableChowMeinActionPerformed
        int menuID = 40;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_SpicyVegetableChowMeinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderVegetarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderVegetarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderVegetarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderVegetarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderVegetarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton FakeChickenChowMein;
    private javax.swing.JButton FakeChickenCurry;
    private javax.swing.JButton MushroomChowMein;
    private javax.swing.JButton MushroomCurry;
    private javax.swing.JButton SpicyVegetableChowMein;
    private javax.swing.JButton SpicyVegetableCurry;
    private javax.swing.JButton TofuChowMein;
    private javax.swing.JButton TofuCurry;
    private javax.swing.JButton VegetableChowMein;
    private javax.swing.JButton VegetableCurry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
