/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courseworkprototype;

/**
 *
 * @author natja
 */
public class OrderNoodles extends javax.swing.JFrame {

    /**
     * Creates new form OrderNoodles
     */
    public OrderNoodles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SingaporeChow = new javax.swing.JButton();
        FriedChow = new javax.swing.JButton();
        MixedChow = new javax.swing.JButton();
        HouseChow = new javax.swing.JButton();
        ChickenChow = new javax.swing.JButton();
        BeefChow = new javax.swing.JButton();
        PorkChow = new javax.swing.JButton();
        DuckChow = new javax.swing.JButton();
        PrawnChow = new javax.swing.JButton();
        ShrimpChow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jLabel1.setText("Noodle Dishes");

        SingaporeChow.setText("Singapore Chow Mein");
        SingaporeChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingaporeChowActionPerformed(evt);
            }
        });

        FriedChow.setText("Fried Chow Mein");
        FriedChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriedChowActionPerformed(evt);
            }
        });

        MixedChow.setText("Mixed Meat Chow Mein");
        MixedChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MixedChowActionPerformed(evt);
            }
        });

        HouseChow.setText("House Special Chow Mein");
        HouseChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HouseChowActionPerformed(evt);
            }
        });

        ChickenChow.setText("Chicken Chow Mein");
        ChickenChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenChowActionPerformed(evt);
            }
        });

        BeefChow.setText("Beef Chow Mein");
        BeefChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeefChowActionPerformed(evt);
            }
        });

        PorkChow.setText("Pork Chow mein");
        PorkChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PorkChowActionPerformed(evt);
            }
        });

        DuckChow.setText("Shredded Duck Chow Mein");
        DuckChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuckChowActionPerformed(evt);
            }
        });

        PrawnChow.setText("King Prawn Chow Mein");
        PrawnChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrawnChowActionPerformed(evt);
            }
        });

        ShrimpChow.setText("Shrimp Chow Mein");
        ShrimpChow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShrimpChowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Back)
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DuckChow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrawnChow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PorkChow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BeefChow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChickenChow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MixedChow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FriedChow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SingaporeChow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ShrimpChow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HouseChow, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChickenChow)
                    .addComponent(ShrimpChow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BeefChow)
                    .addComponent(SingaporeChow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PorkChow)
                    .addComponent(FriedChow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DuckChow)
                    .addComponent(MixedChow))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrawnChow)
                    .addComponent(HouseChow))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        OrderMain f2= new  OrderMain();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void PorkChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PorkChowActionPerformed
        int menuID = 3;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_PorkChowActionPerformed

    private void HouseChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HouseChowActionPerformed
        int menuID = 10;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_HouseChowActionPerformed

    private void BeefChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeefChowActionPerformed
        int menuID = 2;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_BeefChowActionPerformed

    private void ShrimpChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShrimpChowActionPerformed
        int menuID = 6;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_ShrimpChowActionPerformed

    private void ChickenChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenChowActionPerformed
        int menuID = 1;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_ChickenChowActionPerformed

    private void MixedChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MixedChowActionPerformed
        int menuID = 9;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_MixedChowActionPerformed

    private void DuckChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuckChowActionPerformed
        int menuID = 4;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_DuckChowActionPerformed

    private void PrawnChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrawnChowActionPerformed
        int menuID = 5;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_PrawnChowActionPerformed

    private void SingaporeChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingaporeChowActionPerformed
        int menuID = 7;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_SingaporeChowActionPerformed

    private void FriedChowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriedChowActionPerformed
        int menuID = 8;
        OrderMain.orderList(menuID);
    }//GEN-LAST:event_FriedChowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderNoodles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderNoodles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderNoodles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderNoodles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderNoodles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BeefChow;
    private javax.swing.JButton ChickenChow;
    private javax.swing.JButton DuckChow;
    private javax.swing.JButton FriedChow;
    private javax.swing.JButton HouseChow;
    private javax.swing.JButton MixedChow;
    private javax.swing.JButton PorkChow;
    private javax.swing.JButton PrawnChow;
    private javax.swing.JButton ShrimpChow;
    private javax.swing.JButton SingaporeChow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
