/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package courseworkprototype;

/**
 *
 * @author natja
 */
public class PrototypeGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrototypeGUI
     */
    public PrototypeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateOrder = new javax.swing.JButton();
        CheckOrders = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateOrder.setBackground(new java.awt.Color(204, 204, 204));
        CreateOrder.setText("Create New Order");
        CreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateOrderActionPerformed(evt);
            }
        });
        getContentPane().add(CreateOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 140, -1));

        CheckOrders.setBackground(new java.awt.Color(204, 204, 204));
        CheckOrders.setText("Check Orders");
        CheckOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(CheckOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        Exit.setBackground(new java.awt.Color(204, 204, 204));
        Exit.setText("Exit");
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 140, -1));

        jButton1.setText("Active Orders");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateOrderActionPerformed
       NewOrder f2= new  NewOrder();
       f2.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_CreateOrderActionPerformed

    private void CheckOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOrdersActionPerformed
        SearchOrders f2 = new SearchOrders();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CheckOrdersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ActiveOrders f2 = new ActiveOrders();
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrototypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrototypeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOrders;
    private javax.swing.JButton CreateOrder;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
